// <auto-generated />
using System;
using Marketplace.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marketplace.API.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    partial class MarketplaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Marketplace.API.Models.Domain.GeneralListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RandomIntProperty")
                        .HasColumnType("int");

                    b.Property<string>("ReasonOfSale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GeneralListings");

                    b.HasDiscriminator<string>("Discriminator").HasValue("GeneralListing");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ee116e1-24c8-4421-97ec-75d6904d33c7"),
                            Description = "Easy",
                            RandomIntProperty = 1,
                            ReasonOfSale = "I don't need it anymore"
                        });
                });

            modelBuilder.Entity("Marketplace.API.Models.Domain.Clothes", b =>
                {
                    b.HasBaseType("Marketplace.API.Models.Domain.GeneralListing");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("RandomProperty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Clothes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cacdc277-499a-4232-95f5-a5e1f5767d1c"),
                            Description = "A nice shirt",
                            RandomIntProperty = 2,
                            ReasonOfSale = "I don't need it anymore",
                            Gender = 2,
                            RandomProperty = "Random",
                            Size = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
